//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ThreadExample {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("FFMWSWDataSet")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class FFMWSWDataSet : System.Data.DataSet {
        
        private MF_Transcriber_Work_AllocationDataTable tableMF_Transcriber_Work_Allocation;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public FFMWSWDataSet() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected FFMWSWDataSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["MF_Transcriber_Work_Allocation"] != null)) {
                    base.Tables.Add(new MF_Transcriber_Work_AllocationDataTable(ds.Tables["MF_Transcriber_Work_Allocation"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public MF_Transcriber_Work_AllocationDataTable MF_Transcriber_Work_Allocation {
            get {
                return this.tableMF_Transcriber_Work_Allocation;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            FFMWSWDataSet cln = ((FFMWSWDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["MF_Transcriber_Work_Allocation"] != null)) {
                    base.Tables.Add(new MF_Transcriber_Work_AllocationDataTable(ds.Tables["MF_Transcriber_Work_Allocation"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableMF_Transcriber_Work_Allocation = ((MF_Transcriber_Work_AllocationDataTable)(base.Tables["MF_Transcriber_Work_Allocation"]));
            if ((initTable == true)) {
                if ((this.tableMF_Transcriber_Work_Allocation != null)) {
                    this.tableMF_Transcriber_Work_Allocation.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "FFMWSWDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/FFMWSWDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableMF_Transcriber_Work_Allocation = new MF_Transcriber_Work_AllocationDataTable();
            base.Tables.Add(this.tableMF_Transcriber_Work_Allocation);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeMF_Transcriber_Work_Allocation() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            FFMWSWDataSet ds = new FFMWSWDataSet();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void MF_Transcriber_Work_AllocationRowChangeEventHandler(object sender, MF_Transcriber_Work_AllocationRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class MF_Transcriber_Work_AllocationDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnTW_WaveID;
            
            private System.Data.DataColumn columnTW_DocID;
            
            private System.Data.DataColumn columnTW_VsGlobalID;
            
            private System.Data.DataColumn columnTW_TimeOfAllocation;
            
            private System.Data.DataColumn columnTW_Manual;
            
            private System.Data.DataColumn columnTW_MechineName;
            
            private System.Data.DataColumn columnTW_Status;
            
            private System.Data.DataColumn columnTW_Purpose;
            
            private System.Data.DataColumn columnTW_TimeOfTransferEnd;
            
            private System.Data.DataColumn columnTW_TempAllocation;
            
            private System.Data.DataColumn columnTW_UserTurnAround;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public MF_Transcriber_Work_AllocationDataTable() {
                this.TableName = "MF_Transcriber_Work_Allocation";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal MF_Transcriber_Work_AllocationDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected MF_Transcriber_Work_AllocationDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TW_WaveIDColumn {
                get {
                    return this.columnTW_WaveID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TW_DocIDColumn {
                get {
                    return this.columnTW_DocID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TW_VsGlobalIDColumn {
                get {
                    return this.columnTW_VsGlobalID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TW_TimeOfAllocationColumn {
                get {
                    return this.columnTW_TimeOfAllocation;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TW_ManualColumn {
                get {
                    return this.columnTW_Manual;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TW_MechineNameColumn {
                get {
                    return this.columnTW_MechineName;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TW_StatusColumn {
                get {
                    return this.columnTW_Status;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TW_PurposeColumn {
                get {
                    return this.columnTW_Purpose;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TW_TimeOfTransferEndColumn {
                get {
                    return this.columnTW_TimeOfTransferEnd;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TW_TempAllocationColumn {
                get {
                    return this.columnTW_TempAllocation;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TW_UserTurnAroundColumn {
                get {
                    return this.columnTW_UserTurnAround;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public MF_Transcriber_Work_AllocationRow this[int index] {
                get {
                    return ((MF_Transcriber_Work_AllocationRow)(this.Rows[index]));
                }
            }
            
            public event MF_Transcriber_Work_AllocationRowChangeEventHandler MF_Transcriber_Work_AllocationRowChanging;
            
            public event MF_Transcriber_Work_AllocationRowChangeEventHandler MF_Transcriber_Work_AllocationRowChanged;
            
            public event MF_Transcriber_Work_AllocationRowChangeEventHandler MF_Transcriber_Work_AllocationRowDeleting;
            
            public event MF_Transcriber_Work_AllocationRowChangeEventHandler MF_Transcriber_Work_AllocationRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddMF_Transcriber_Work_AllocationRow(MF_Transcriber_Work_AllocationRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public MF_Transcriber_Work_AllocationRow AddMF_Transcriber_Work_AllocationRow(decimal TW_WaveID, decimal TW_DocID, decimal TW_VsGlobalID, System.DateTime TW_TimeOfAllocation, int TW_Manual, string TW_MechineName, int TW_Status, int TW_Purpose, System.DateTime TW_TimeOfTransferEnd, bool TW_TempAllocation, int TW_UserTurnAround) {
                MF_Transcriber_Work_AllocationRow rowMF_Transcriber_Work_AllocationRow = ((MF_Transcriber_Work_AllocationRow)(this.NewRow()));
                rowMF_Transcriber_Work_AllocationRow.ItemArray = new object[] {
                        TW_WaveID,
                        TW_DocID,
                        TW_VsGlobalID,
                        TW_TimeOfAllocation,
                        TW_Manual,
                        TW_MechineName,
                        TW_Status,
                        TW_Purpose,
                        TW_TimeOfTransferEnd,
                        TW_TempAllocation,
                        TW_UserTurnAround};
                this.Rows.Add(rowMF_Transcriber_Work_AllocationRow);
                return rowMF_Transcriber_Work_AllocationRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public MF_Transcriber_Work_AllocationRow FindByTW_WaveIDTW_DocIDTW_VsGlobalIDTW_Purpose(decimal TW_WaveID, decimal TW_DocID, decimal TW_VsGlobalID, int TW_Purpose) {
                return ((MF_Transcriber_Work_AllocationRow)(this.Rows.Find(new object[] {
                            TW_WaveID,
                            TW_DocID,
                            TW_VsGlobalID,
                            TW_Purpose})));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                MF_Transcriber_Work_AllocationDataTable cln = ((MF_Transcriber_Work_AllocationDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new MF_Transcriber_Work_AllocationDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnTW_WaveID = base.Columns["TW_WaveID"];
                this.columnTW_DocID = base.Columns["TW_DocID"];
                this.columnTW_VsGlobalID = base.Columns["TW_VsGlobalID"];
                this.columnTW_TimeOfAllocation = base.Columns["TW_TimeOfAllocation"];
                this.columnTW_Manual = base.Columns["TW_Manual"];
                this.columnTW_MechineName = base.Columns["TW_MechineName"];
                this.columnTW_Status = base.Columns["TW_Status"];
                this.columnTW_Purpose = base.Columns["TW_Purpose"];
                this.columnTW_TimeOfTransferEnd = base.Columns["TW_TimeOfTransferEnd"];
                this.columnTW_TempAllocation = base.Columns["TW_TempAllocation"];
                this.columnTW_UserTurnAround = base.Columns["TW_UserTurnAround"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnTW_WaveID = new System.Data.DataColumn("TW_WaveID", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTW_WaveID);
                this.columnTW_DocID = new System.Data.DataColumn("TW_DocID", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTW_DocID);
                this.columnTW_VsGlobalID = new System.Data.DataColumn("TW_VsGlobalID", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTW_VsGlobalID);
                this.columnTW_TimeOfAllocation = new System.Data.DataColumn("TW_TimeOfAllocation", typeof(System.DateTime), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTW_TimeOfAllocation);
                this.columnTW_Manual = new System.Data.DataColumn("TW_Manual", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTW_Manual);
                this.columnTW_MechineName = new System.Data.DataColumn("TW_MechineName", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTW_MechineName);
                this.columnTW_Status = new System.Data.DataColumn("TW_Status", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTW_Status);
                this.columnTW_Purpose = new System.Data.DataColumn("TW_Purpose", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTW_Purpose);
                this.columnTW_TimeOfTransferEnd = new System.Data.DataColumn("TW_TimeOfTransferEnd", typeof(System.DateTime), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTW_TimeOfTransferEnd);
                this.columnTW_TempAllocation = new System.Data.DataColumn("TW_TempAllocation", typeof(bool), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTW_TempAllocation);
                this.columnTW_UserTurnAround = new System.Data.DataColumn("TW_UserTurnAround", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTW_UserTurnAround);
                this.Constraints.Add(new System.Data.UniqueConstraint("Constraint1", new System.Data.DataColumn[] {
                                this.columnTW_WaveID,
                                this.columnTW_DocID,
                                this.columnTW_VsGlobalID,
                                this.columnTW_Purpose}, true));
                this.columnTW_WaveID.AllowDBNull = false;
                this.columnTW_DocID.AllowDBNull = false;
                this.columnTW_VsGlobalID.AllowDBNull = false;
                this.columnTW_TimeOfAllocation.AllowDBNull = false;
                this.columnTW_Manual.AllowDBNull = false;
                this.columnTW_MechineName.MaxLength = 50;
                this.columnTW_Status.AllowDBNull = false;
                this.columnTW_Purpose.AllowDBNull = false;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public MF_Transcriber_Work_AllocationRow NewMF_Transcriber_Work_AllocationRow() {
                return ((MF_Transcriber_Work_AllocationRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new MF_Transcriber_Work_AllocationRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(MF_Transcriber_Work_AllocationRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.MF_Transcriber_Work_AllocationRowChanged != null)) {
                    this.MF_Transcriber_Work_AllocationRowChanged(this, new MF_Transcriber_Work_AllocationRowChangeEvent(((MF_Transcriber_Work_AllocationRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.MF_Transcriber_Work_AllocationRowChanging != null)) {
                    this.MF_Transcriber_Work_AllocationRowChanging(this, new MF_Transcriber_Work_AllocationRowChangeEvent(((MF_Transcriber_Work_AllocationRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.MF_Transcriber_Work_AllocationRowDeleted != null)) {
                    this.MF_Transcriber_Work_AllocationRowDeleted(this, new MF_Transcriber_Work_AllocationRowChangeEvent(((MF_Transcriber_Work_AllocationRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.MF_Transcriber_Work_AllocationRowDeleting != null)) {
                    this.MF_Transcriber_Work_AllocationRowDeleting(this, new MF_Transcriber_Work_AllocationRowChangeEvent(((MF_Transcriber_Work_AllocationRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveMF_Transcriber_Work_AllocationRow(MF_Transcriber_Work_AllocationRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                FFMWSWDataSet ds = new FFMWSWDataSet();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "MF_Transcriber_Work_AllocationDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class MF_Transcriber_Work_AllocationRow : System.Data.DataRow {
            
            private MF_Transcriber_Work_AllocationDataTable tableMF_Transcriber_Work_Allocation;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal MF_Transcriber_Work_AllocationRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableMF_Transcriber_Work_Allocation = ((MF_Transcriber_Work_AllocationDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal TW_WaveID {
                get {
                    return ((decimal)(this[this.tableMF_Transcriber_Work_Allocation.TW_WaveIDColumn]));
                }
                set {
                    this[this.tableMF_Transcriber_Work_Allocation.TW_WaveIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal TW_DocID {
                get {
                    return ((decimal)(this[this.tableMF_Transcriber_Work_Allocation.TW_DocIDColumn]));
                }
                set {
                    this[this.tableMF_Transcriber_Work_Allocation.TW_DocIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal TW_VsGlobalID {
                get {
                    return ((decimal)(this[this.tableMF_Transcriber_Work_Allocation.TW_VsGlobalIDColumn]));
                }
                set {
                    this[this.tableMF_Transcriber_Work_Allocation.TW_VsGlobalIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime TW_TimeOfAllocation {
                get {
                    return ((System.DateTime)(this[this.tableMF_Transcriber_Work_Allocation.TW_TimeOfAllocationColumn]));
                }
                set {
                    this[this.tableMF_Transcriber_Work_Allocation.TW_TimeOfAllocationColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int TW_Manual {
                get {
                    return ((int)(this[this.tableMF_Transcriber_Work_Allocation.TW_ManualColumn]));
                }
                set {
                    this[this.tableMF_Transcriber_Work_Allocation.TW_ManualColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TW_MechineName {
                get {
                    try {
                        return ((string)(this[this.tableMF_Transcriber_Work_Allocation.TW_MechineNameColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'TW_MechineName\' in table \'MF_Transcriber_Work_Allocation\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableMF_Transcriber_Work_Allocation.TW_MechineNameColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int TW_Status {
                get {
                    return ((int)(this[this.tableMF_Transcriber_Work_Allocation.TW_StatusColumn]));
                }
                set {
                    this[this.tableMF_Transcriber_Work_Allocation.TW_StatusColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int TW_Purpose {
                get {
                    return ((int)(this[this.tableMF_Transcriber_Work_Allocation.TW_PurposeColumn]));
                }
                set {
                    this[this.tableMF_Transcriber_Work_Allocation.TW_PurposeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime TW_TimeOfTransferEnd {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableMF_Transcriber_Work_Allocation.TW_TimeOfTransferEndColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'TW_TimeOfTransferEnd\' in table \'MF_Transcriber_Work_Allocat" +
                                "ion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMF_Transcriber_Work_Allocation.TW_TimeOfTransferEndColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool TW_TempAllocation {
                get {
                    try {
                        return ((bool)(this[this.tableMF_Transcriber_Work_Allocation.TW_TempAllocationColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'TW_TempAllocation\' in table \'MF_Transcriber_Work_Allocation" +
                                "\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMF_Transcriber_Work_Allocation.TW_TempAllocationColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int TW_UserTurnAround {
                get {
                    try {
                        return ((int)(this[this.tableMF_Transcriber_Work_Allocation.TW_UserTurnAroundColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'TW_UserTurnAround\' in table \'MF_Transcriber_Work_Allocation" +
                                "\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMF_Transcriber_Work_Allocation.TW_UserTurnAroundColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTW_MechineNameNull() {
                return this.IsNull(this.tableMF_Transcriber_Work_Allocation.TW_MechineNameColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTW_MechineNameNull() {
                this[this.tableMF_Transcriber_Work_Allocation.TW_MechineNameColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTW_TimeOfTransferEndNull() {
                return this.IsNull(this.tableMF_Transcriber_Work_Allocation.TW_TimeOfTransferEndColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTW_TimeOfTransferEndNull() {
                this[this.tableMF_Transcriber_Work_Allocation.TW_TimeOfTransferEndColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTW_TempAllocationNull() {
                return this.IsNull(this.tableMF_Transcriber_Work_Allocation.TW_TempAllocationColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTW_TempAllocationNull() {
                this[this.tableMF_Transcriber_Work_Allocation.TW_TempAllocationColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTW_UserTurnAroundNull() {
                return this.IsNull(this.tableMF_Transcriber_Work_Allocation.TW_UserTurnAroundColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTW_UserTurnAroundNull() {
                this[this.tableMF_Transcriber_Work_Allocation.TW_UserTurnAroundColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class MF_Transcriber_Work_AllocationRowChangeEvent : System.EventArgs {
            
            private MF_Transcriber_Work_AllocationRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public MF_Transcriber_Work_AllocationRowChangeEvent(MF_Transcriber_Work_AllocationRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public MF_Transcriber_Work_AllocationRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace ThreadExample.FFMWSWDataSetTableAdapters {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.ComponentModel.DataObjectAttribute(true)]
    [System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class MF_Transcriber_Work_AllocationTableAdapter : System.ComponentModel.Component {
        
        private System.Data.SqlClient.SqlDataAdapter _adapter;
        
        private System.Data.SqlClient.SqlConnection _connection;
        
        private System.Data.SqlClient.SqlCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public MF_Transcriber_Work_AllocationTableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private System.Data.SqlClient.SqlDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal System.Data.SqlClient.SqlConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((System.Data.SqlClient.SqlCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected System.Data.SqlClient.SqlCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new System.Data.SqlClient.SqlDataAdapter();
            System.Data.Common.DataTableMapping tableMapping = new System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "MF_Transcriber_Work_Allocation";
            tableMapping.ColumnMappings.Add("TW_WaveID", "TW_WaveID");
            tableMapping.ColumnMappings.Add("TW_DocID", "TW_DocID");
            tableMapping.ColumnMappings.Add("TW_VsGlobalID", "TW_VsGlobalID");
            tableMapping.ColumnMappings.Add("TW_TimeOfAllocation", "TW_TimeOfAllocation");
            tableMapping.ColumnMappings.Add("TW_Manual", "TW_Manual");
            tableMapping.ColumnMappings.Add("TW_MechineName", "TW_MechineName");
            tableMapping.ColumnMappings.Add("TW_Status", "TW_Status");
            tableMapping.ColumnMappings.Add("TW_Purpose", "TW_Purpose");
            tableMapping.ColumnMappings.Add("TW_TimeOfTransferEnd", "TW_TimeOfTransferEnd");
            tableMapping.ColumnMappings.Add("TW_TempAllocation", "TW_TempAllocation");
            tableMapping.ColumnMappings.Add("TW_UserTurnAround", "TW_UserTurnAround");
            this._adapter.TableMappings.Add(tableMapping);
            this._adapter.DeleteCommand = new System.Data.SqlClient.SqlCommand();
            this._adapter.DeleteCommand.Connection = this.Connection;
            this._adapter.DeleteCommand.CommandText = @"DELETE FROM [dbo].[MF_Transcriber_Work_Allocation] WHERE (([TW_WaveID] = @Original_TW_WaveID) AND ([TW_DocID] = @Original_TW_DocID) AND ([TW_VsGlobalID] = @Original_TW_VsGlobalID) AND ([TW_TimeOfAllocation] = @Original_TW_TimeOfAllocation) AND ([TW_Manual] = @Original_TW_Manual) AND ((@IsNull_TW_MechineName = 1 AND [TW_MechineName] IS NULL) OR ([TW_MechineName] = @Original_TW_MechineName)) AND ([TW_Status] = @Original_TW_Status) AND ([TW_Purpose] = @Original_TW_Purpose) AND ((@IsNull_TW_TimeOfTransferEnd = 1 AND [TW_TimeOfTransferEnd] IS NULL) OR ([TW_TimeOfTransferEnd] = @Original_TW_TimeOfTransferEnd)) AND ((@IsNull_TW_TempAllocation = 1 AND [TW_TempAllocation] IS NULL) OR ([TW_TempAllocation] = @Original_TW_TempAllocation)) AND ((@IsNull_TW_UserTurnAround = 1 AND [TW_UserTurnAround] IS NULL) OR ([TW_UserTurnAround] = @Original_TW_UserTurnAround)))";
            this._adapter.DeleteCommand.CommandType = System.Data.CommandType.Text;
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_WaveID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_WaveID", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_DocID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_DocID", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_VsGlobalID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_VsGlobalID", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_TimeOfAllocation", System.Data.SqlDbType.DateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TimeOfAllocation", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_Manual", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Manual", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@IsNull_TW_MechineName", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_MechineName", System.Data.DataRowVersion.Original, true, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_MechineName", System.Data.SqlDbType.VarChar, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_MechineName", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_Status", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Status", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_Purpose", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Purpose", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@IsNull_TW_TimeOfTransferEnd", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TimeOfTransferEnd", System.Data.DataRowVersion.Original, true, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_TimeOfTransferEnd", System.Data.SqlDbType.DateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TimeOfTransferEnd", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@IsNull_TW_TempAllocation", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TempAllocation", System.Data.DataRowVersion.Original, true, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_TempAllocation", System.Data.SqlDbType.Bit, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TempAllocation", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@IsNull_TW_UserTurnAround", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_UserTurnAround", System.Data.DataRowVersion.Original, true, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_UserTurnAround", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_UserTurnAround", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.InsertCommand = new System.Data.SqlClient.SqlCommand();
            this._adapter.InsertCommand.Connection = this.Connection;
            this._adapter.InsertCommand.CommandText = @"INSERT INTO [dbo].[MF_Transcriber_Work_Allocation] ([TW_WaveID], [TW_DocID], [TW_VsGlobalID], [TW_TimeOfAllocation], [TW_Manual], [TW_MechineName], [TW_Status], [TW_Purpose], [TW_TimeOfTransferEnd], [TW_TempAllocation], [TW_UserTurnAround]) VALUES (@TW_WaveID, @TW_DocID, @TW_VsGlobalID, @TW_TimeOfAllocation, @TW_Manual, @TW_MechineName, @TW_Status, @TW_Purpose, @TW_TimeOfTransferEnd, @TW_TempAllocation, @TW_UserTurnAround);
SELECT TW_WaveID, TW_DocID, TW_VsGlobalID, TW_TimeOfAllocation, TW_Manual, TW_MechineName, TW_Status, TW_Purpose, TW_TimeOfTransferEnd, TW_TempAllocation, TW_UserTurnAround FROM MF_Transcriber_Work_Allocation WHERE (TW_DocID = @TW_DocID) AND (TW_Purpose = @TW_Purpose) AND (TW_VsGlobalID = @TW_VsGlobalID) AND (TW_WaveID = @TW_WaveID)";
            this._adapter.InsertCommand.CommandType = System.Data.CommandType.Text;
            this._adapter.InsertCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_WaveID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_WaveID", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_DocID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_DocID", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_VsGlobalID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_VsGlobalID", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_TimeOfAllocation", System.Data.SqlDbType.DateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TimeOfAllocation", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_Manual", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Manual", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_MechineName", System.Data.SqlDbType.VarChar, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_MechineName", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_Status", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Status", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_Purpose", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Purpose", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_TimeOfTransferEnd", System.Data.SqlDbType.DateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TimeOfTransferEnd", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_TempAllocation", System.Data.SqlDbType.Bit, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TempAllocation", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_UserTurnAround", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_UserTurnAround", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand = new System.Data.SqlClient.SqlCommand();
            this._adapter.UpdateCommand.Connection = this.Connection;
            this._adapter.UpdateCommand.CommandText = "UPDATE [dbo].[MF_Transcriber_Work_Allocation] SET [TW_WaveID] = @TW_WaveID, [TW_D" +
                "ocID] = @TW_DocID, [TW_VsGlobalID] = @TW_VsGlobalID, [TW_TimeOfAllocation] = @TW" +
                "_TimeOfAllocation, [TW_Manual] = @TW_Manual, [TW_MechineName] = @TW_MechineName," +
                " [TW_Status] = @TW_Status, [TW_Purpose] = @TW_Purpose, [TW_TimeOfTransferEnd] = " +
                "@TW_TimeOfTransferEnd, [TW_TempAllocation] = @TW_TempAllocation, [TW_UserTurnAro" +
                "und] = @TW_UserTurnAround WHERE (([TW_WaveID] = @Original_TW_WaveID) AND ([TW_Do" +
                "cID] = @Original_TW_DocID) AND ([TW_VsGlobalID] = @Original_TW_VsGlobalID) AND (" +
                "[TW_TimeOfAllocation] = @Original_TW_TimeOfAllocation) AND ([TW_Manual] = @Origi" +
                "nal_TW_Manual) AND ((@IsNull_TW_MechineName = 1 AND [TW_MechineName] IS NULL) OR" +
                " ([TW_MechineName] = @Original_TW_MechineName)) AND ([TW_Status] = @Original_TW_" +
                "Status) AND ([TW_Purpose] = @Original_TW_Purpose) AND ((@IsNull_TW_TimeOfTransfe" +
                "rEnd = 1 AND [TW_TimeOfTransferEnd] IS NULL) OR ([TW_TimeOfTransferEnd] = @Origi" +
                "nal_TW_TimeOfTransferEnd)) AND ((@IsNull_TW_TempAllocation = 1 AND [TW_TempAlloc" +
                "ation] IS NULL) OR ([TW_TempAllocation] = @Original_TW_TempAllocation)) AND ((@I" +
                "sNull_TW_UserTurnAround = 1 AND [TW_UserTurnAround] IS NULL) OR ([TW_UserTurnAro" +
                "und] = @Original_TW_UserTurnAround)));\r\nSELECT TW_WaveID, TW_DocID, TW_VsGlobalI" +
                "D, TW_TimeOfAllocation, TW_Manual, TW_MechineName, TW_Status, TW_Purpose, TW_Tim" +
                "eOfTransferEnd, TW_TempAllocation, TW_UserTurnAround FROM MF_Transcriber_Work_Al" +
                "location WHERE (TW_DocID = @TW_DocID) AND (TW_Purpose = @TW_Purpose) AND (TW_VsG" +
                "lobalID = @TW_VsGlobalID) AND (TW_WaveID = @TW_WaveID)";
            this._adapter.UpdateCommand.CommandType = System.Data.CommandType.Text;
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_WaveID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_WaveID", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_DocID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_DocID", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_VsGlobalID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_VsGlobalID", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_TimeOfAllocation", System.Data.SqlDbType.DateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TimeOfAllocation", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_Manual", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Manual", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_MechineName", System.Data.SqlDbType.VarChar, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_MechineName", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_Status", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Status", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_Purpose", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Purpose", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_TimeOfTransferEnd", System.Data.SqlDbType.DateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TimeOfTransferEnd", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_TempAllocation", System.Data.SqlDbType.Bit, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TempAllocation", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@TW_UserTurnAround", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_UserTurnAround", System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_WaveID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_WaveID", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_DocID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_DocID", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_VsGlobalID", System.Data.SqlDbType.Decimal, 0, System.Data.ParameterDirection.Input, 10, 0, "TW_VsGlobalID", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_TimeOfAllocation", System.Data.SqlDbType.DateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TimeOfAllocation", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_Manual", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Manual", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@IsNull_TW_MechineName", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_MechineName", System.Data.DataRowVersion.Original, true, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_MechineName", System.Data.SqlDbType.VarChar, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_MechineName", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_Status", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Status", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_Purpose", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_Purpose", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@IsNull_TW_TimeOfTransferEnd", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TimeOfTransferEnd", System.Data.DataRowVersion.Original, true, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_TimeOfTransferEnd", System.Data.SqlDbType.DateTime, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TimeOfTransferEnd", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@IsNull_TW_TempAllocation", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TempAllocation", System.Data.DataRowVersion.Original, true, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_TempAllocation", System.Data.SqlDbType.Bit, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_TempAllocation", System.Data.DataRowVersion.Original, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@IsNull_TW_UserTurnAround", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_UserTurnAround", System.Data.DataRowVersion.Original, true, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new System.Data.SqlClient.SqlParameter("@Original_TW_UserTurnAround", System.Data.SqlDbType.Int, 0, System.Data.ParameterDirection.Input, 0, 0, "TW_UserTurnAround", System.Data.DataRowVersion.Original, false, null, "", "", ""));
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new System.Data.SqlClient.SqlConnection();
            this._connection.ConnectionString = global::ThreadExample.Properties.Settings.Default.FFMWSWConnectionString;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new System.Data.SqlClient.SqlCommand[1];
            this._commandCollection[0] = new System.Data.SqlClient.SqlCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "SELECT TW_WaveID, TW_DocID, TW_VsGlobalID, TW_TimeOfAllocation, TW_Manual, TW_Mec" +
                "hineName, TW_Status, TW_Purpose, TW_TimeOfTransferEnd, TW_TempAllocation, TW_Use" +
                "rTurnAround FROM dbo.MF_Transcriber_Work_Allocation";
            this._commandCollection[0].CommandType = System.Data.CommandType.Text;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(FFMWSWDataSet.MF_Transcriber_Work_AllocationDataTable dataTable) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual FFMWSWDataSet.MF_Transcriber_Work_AllocationDataTable GetData() {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            FFMWSWDataSet.MF_Transcriber_Work_AllocationDataTable dataTable = new FFMWSWDataSet.MF_Transcriber_Work_AllocationDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(FFMWSWDataSet.MF_Transcriber_Work_AllocationDataTable dataTable) {
            return this.Adapter.Update(dataTable);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(FFMWSWDataSet dataSet) {
            return this.Adapter.Update(dataSet, "MF_Transcriber_Work_Allocation");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(System.Data.DataRow dataRow) {
            return this.Adapter.Update(new System.Data.DataRow[] {
                        dataRow});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(System.Data.DataRow[] dataRows) {
            return this.Adapter.Update(dataRows);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public virtual int Delete(decimal Original_TW_WaveID, decimal Original_TW_DocID, decimal Original_TW_VsGlobalID, System.DateTime Original_TW_TimeOfAllocation, int Original_TW_Manual, string Original_TW_MechineName, int Original_TW_Status, int Original_TW_Purpose, System.Nullable<System.DateTime> Original_TW_TimeOfTransferEnd, System.Nullable<bool> Original_TW_TempAllocation, System.Nullable<int> Original_TW_UserTurnAround) {
            this.Adapter.DeleteCommand.Parameters[0].Value = ((decimal)(Original_TW_WaveID));
            this.Adapter.DeleteCommand.Parameters[1].Value = ((decimal)(Original_TW_DocID));
            this.Adapter.DeleteCommand.Parameters[2].Value = ((decimal)(Original_TW_VsGlobalID));
            this.Adapter.DeleteCommand.Parameters[3].Value = ((System.DateTime)(Original_TW_TimeOfAllocation));
            this.Adapter.DeleteCommand.Parameters[4].Value = ((int)(Original_TW_Manual));
            if ((Original_TW_MechineName == null)) {
                this.Adapter.DeleteCommand.Parameters[5].Value = ((object)(1));
                this.Adapter.DeleteCommand.Parameters[6].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.DeleteCommand.Parameters[5].Value = ((object)(0));
                this.Adapter.DeleteCommand.Parameters[6].Value = ((string)(Original_TW_MechineName));
            }
            this.Adapter.DeleteCommand.Parameters[7].Value = ((int)(Original_TW_Status));
            this.Adapter.DeleteCommand.Parameters[8].Value = ((int)(Original_TW_Purpose));
            if ((Original_TW_TimeOfTransferEnd.HasValue == true)) {
                this.Adapter.DeleteCommand.Parameters[9].Value = ((object)(0));
                this.Adapter.DeleteCommand.Parameters[10].Value = ((System.DateTime)(Original_TW_TimeOfTransferEnd.Value));
            }
            else {
                this.Adapter.DeleteCommand.Parameters[9].Value = ((object)(1));
                this.Adapter.DeleteCommand.Parameters[10].Value = System.DBNull.Value;
            }
            if ((Original_TW_TempAllocation.HasValue == true)) {
                this.Adapter.DeleteCommand.Parameters[11].Value = ((object)(0));
                this.Adapter.DeleteCommand.Parameters[12].Value = ((bool)(Original_TW_TempAllocation.Value));
            }
            else {
                this.Adapter.DeleteCommand.Parameters[11].Value = ((object)(1));
                this.Adapter.DeleteCommand.Parameters[12].Value = System.DBNull.Value;
            }
            if ((Original_TW_UserTurnAround.HasValue == true)) {
                this.Adapter.DeleteCommand.Parameters[13].Value = ((object)(0));
                this.Adapter.DeleteCommand.Parameters[14].Value = ((int)(Original_TW_UserTurnAround.Value));
            }
            else {
                this.Adapter.DeleteCommand.Parameters[13].Value = ((object)(1));
                this.Adapter.DeleteCommand.Parameters[14].Value = System.DBNull.Value;
            }
            System.Data.ConnectionState previousConnectionState = this.Adapter.DeleteCommand.Connection.State;
            if (((this.Adapter.DeleteCommand.Connection.State & System.Data.ConnectionState.Open) 
                        != System.Data.ConnectionState.Open)) {
                this.Adapter.DeleteCommand.Connection.Open();
            }
            try {
                int returnValue = this.Adapter.DeleteCommand.ExecuteNonQuery();
                return returnValue;
            }
            finally {
                if ((previousConnectionState == System.Data.ConnectionState.Closed)) {
                    this.Adapter.DeleteCommand.Connection.Close();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public virtual int Insert(decimal TW_WaveID, decimal TW_DocID, decimal TW_VsGlobalID, System.DateTime TW_TimeOfAllocation, int TW_Manual, string TW_MechineName, int TW_Status, int TW_Purpose, System.Nullable<System.DateTime> TW_TimeOfTransferEnd, System.Nullable<bool> TW_TempAllocation, System.Nullable<int> TW_UserTurnAround) {
            this.Adapter.InsertCommand.Parameters[0].Value = ((decimal)(TW_WaveID));
            this.Adapter.InsertCommand.Parameters[1].Value = ((decimal)(TW_DocID));
            this.Adapter.InsertCommand.Parameters[2].Value = ((decimal)(TW_VsGlobalID));
            this.Adapter.InsertCommand.Parameters[3].Value = ((System.DateTime)(TW_TimeOfAllocation));
            this.Adapter.InsertCommand.Parameters[4].Value = ((int)(TW_Manual));
            if ((TW_MechineName == null)) {
                this.Adapter.InsertCommand.Parameters[5].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[5].Value = ((string)(TW_MechineName));
            }
            this.Adapter.InsertCommand.Parameters[6].Value = ((int)(TW_Status));
            this.Adapter.InsertCommand.Parameters[7].Value = ((int)(TW_Purpose));
            if ((TW_TimeOfTransferEnd.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[8].Value = ((System.DateTime)(TW_TimeOfTransferEnd.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[8].Value = System.DBNull.Value;
            }
            if ((TW_TempAllocation.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[9].Value = ((bool)(TW_TempAllocation.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[9].Value = System.DBNull.Value;
            }
            if ((TW_UserTurnAround.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[10].Value = ((int)(TW_UserTurnAround.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[10].Value = System.DBNull.Value;
            }
            System.Data.ConnectionState previousConnectionState = this.Adapter.InsertCommand.Connection.State;
            if (((this.Adapter.InsertCommand.Connection.State & System.Data.ConnectionState.Open) 
                        != System.Data.ConnectionState.Open)) {
                this.Adapter.InsertCommand.Connection.Open();
            }
            try {
                int returnValue = this.Adapter.InsertCommand.ExecuteNonQuery();
                return returnValue;
            }
            finally {
                if ((previousConnectionState == System.Data.ConnectionState.Closed)) {
                    this.Adapter.InsertCommand.Connection.Close();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public virtual int Update(
                    decimal TW_WaveID, 
                    decimal TW_DocID, 
                    decimal TW_VsGlobalID, 
                    System.DateTime TW_TimeOfAllocation, 
                    int TW_Manual, 
                    string TW_MechineName, 
                    int TW_Status, 
                    int TW_Purpose, 
                    System.Nullable<System.DateTime> TW_TimeOfTransferEnd, 
                    System.Nullable<bool> TW_TempAllocation, 
                    System.Nullable<int> TW_UserTurnAround, 
                    decimal Original_TW_WaveID, 
                    decimal Original_TW_DocID, 
                    decimal Original_TW_VsGlobalID, 
                    System.DateTime Original_TW_TimeOfAllocation, 
                    int Original_TW_Manual, 
                    string Original_TW_MechineName, 
                    int Original_TW_Status, 
                    int Original_TW_Purpose, 
                    System.Nullable<System.DateTime> Original_TW_TimeOfTransferEnd, 
                    System.Nullable<bool> Original_TW_TempAllocation, 
                    System.Nullable<int> Original_TW_UserTurnAround) {
            this.Adapter.UpdateCommand.Parameters[0].Value = ((decimal)(TW_WaveID));
            this.Adapter.UpdateCommand.Parameters[1].Value = ((decimal)(TW_DocID));
            this.Adapter.UpdateCommand.Parameters[2].Value = ((decimal)(TW_VsGlobalID));
            this.Adapter.UpdateCommand.Parameters[3].Value = ((System.DateTime)(TW_TimeOfAllocation));
            this.Adapter.UpdateCommand.Parameters[4].Value = ((int)(TW_Manual));
            if ((TW_MechineName == null)) {
                this.Adapter.UpdateCommand.Parameters[5].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.UpdateCommand.Parameters[5].Value = ((string)(TW_MechineName));
            }
            this.Adapter.UpdateCommand.Parameters[6].Value = ((int)(TW_Status));
            this.Adapter.UpdateCommand.Parameters[7].Value = ((int)(TW_Purpose));
            if ((TW_TimeOfTransferEnd.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[8].Value = ((System.DateTime)(TW_TimeOfTransferEnd.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[8].Value = System.DBNull.Value;
            }
            if ((TW_TempAllocation.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[9].Value = ((bool)(TW_TempAllocation.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[9].Value = System.DBNull.Value;
            }
            if ((TW_UserTurnAround.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[10].Value = ((int)(TW_UserTurnAround.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[10].Value = System.DBNull.Value;
            }
            this.Adapter.UpdateCommand.Parameters[11].Value = ((decimal)(Original_TW_WaveID));
            this.Adapter.UpdateCommand.Parameters[12].Value = ((decimal)(Original_TW_DocID));
            this.Adapter.UpdateCommand.Parameters[13].Value = ((decimal)(Original_TW_VsGlobalID));
            this.Adapter.UpdateCommand.Parameters[14].Value = ((System.DateTime)(Original_TW_TimeOfAllocation));
            this.Adapter.UpdateCommand.Parameters[15].Value = ((int)(Original_TW_Manual));
            if ((Original_TW_MechineName == null)) {
                this.Adapter.UpdateCommand.Parameters[16].Value = ((object)(1));
                this.Adapter.UpdateCommand.Parameters[17].Value = System.DBNull.Value;
            }
            else {
                this.Adapter.UpdateCommand.Parameters[16].Value = ((object)(0));
                this.Adapter.UpdateCommand.Parameters[17].Value = ((string)(Original_TW_MechineName));
            }
            this.Adapter.UpdateCommand.Parameters[18].Value = ((int)(Original_TW_Status));
            this.Adapter.UpdateCommand.Parameters[19].Value = ((int)(Original_TW_Purpose));
            if ((Original_TW_TimeOfTransferEnd.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[20].Value = ((object)(0));
                this.Adapter.UpdateCommand.Parameters[21].Value = ((System.DateTime)(Original_TW_TimeOfTransferEnd.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[20].Value = ((object)(1));
                this.Adapter.UpdateCommand.Parameters[21].Value = System.DBNull.Value;
            }
            if ((Original_TW_TempAllocation.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[22].Value = ((object)(0));
                this.Adapter.UpdateCommand.Parameters[23].Value = ((bool)(Original_TW_TempAllocation.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[22].Value = ((object)(1));
                this.Adapter.UpdateCommand.Parameters[23].Value = System.DBNull.Value;
            }
            if ((Original_TW_UserTurnAround.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[24].Value = ((object)(0));
                this.Adapter.UpdateCommand.Parameters[25].Value = ((int)(Original_TW_UserTurnAround.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[24].Value = ((object)(1));
                this.Adapter.UpdateCommand.Parameters[25].Value = System.DBNull.Value;
            }
            System.Data.ConnectionState previousConnectionState = this.Adapter.UpdateCommand.Connection.State;
            if (((this.Adapter.UpdateCommand.Connection.State & System.Data.ConnectionState.Open) 
                        != System.Data.ConnectionState.Open)) {
                this.Adapter.UpdateCommand.Connection.Open();
            }
            try {
                int returnValue = this.Adapter.UpdateCommand.ExecuteNonQuery();
                return returnValue;
            }
            finally {
                if ((previousConnectionState == System.Data.ConnectionState.Closed)) {
                    this.Adapter.UpdateCommand.Connection.Close();
                }
            }
        }
    }
}

#pragma warning restore 1591