/* 
 * Swagger Movie collection
 *
 * This API is used for movie collection
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Message
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageTests
    {
        // TODO uncomment below to declare an instance variable for Message
        //private Message instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Message
            //instance = new Message();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Message
        /// </summary>
        [Test]
        public void MessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Message
            //Assert.IsInstanceOfType<Message> (instance, "variable 'instance' is a Message");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Director'
        /// </summary>
        [Test]
        public void DirectorTest()
        {
            // TODO unit test for the property 'Director'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Test]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'Cast'
        /// </summary>
        [Test]
        public void CastTest()
        {
            // TODO unit test for the property 'Cast'
        }

    }

}
